### ISSUE TITLE
Turning off `allowNormalSpawning` also disables spawners and spawn eggs

### ISSUE THREAD

**Issue by Zarainia** [Darkhax-Minecraft/BadMobs#63]
For example, if I have:

```toml
#Spawning options for minecraft:zombie
[minecraft.zombie]
  #Should the entity be allowed to spawn normally?
  allowNormalSpawning = false
  #Should spawners be able to spawn the entity?
  allowSpawners = true
  #Should spawn eggs be able to spawn the entity?
  allowSpawnEggs = true
  #Should the entity spawn via mob conversion? i.e. villager -> zombie
  allowConversions = true
  #When enabled the entity type will be aggresively removed from worlds. This will bypass all other options.
  removeAggressively = false
```

and use a spawn egg, I hear the zombie noise, but it never spawns. Not sure what could be happening; I looked at the code and it makes sense to me. 

Minecraft version: 1.18.2
Forge version: 40.1.54
Mod version: BadMobs-1.18.2-13.01.jar
